language: python
sudo: false
os: osx
python: 2.7
jobs:
  include:
    - stage: deploy
      if: tag IS present
      deploy:
        provider: pypi
        user: __token__
        password: $PYPI_API_TOKEN
        on:
          tags: true
          all_branches: true